#!/bin/sh

if [ "x$1" = "x-usage" ]; then
  echo push memo to server
  exit
fi

set -Eeu

cd "$MEMODIR"
git add -A --ignore-errors
git commit -m "Commit on $(hostname): $(date '+%Y-%m-%d %H:%M:%S')" || true
git push origin main
