# You may need:
# # echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/99-input.rules
# sudo udevadm trigger
# sudo udevadm control --reload-rules
#
# To allow xremap to fetch the focused app name using D-Bus,
# you need to enable the extension which is in:
#    https://extensions.gnome.org/extension/5060/xremap/
keypress_delay_ms: 10
shared:
  terminals: &terminals
    - "/(?i)terminal/"
    - "/(?i)gvim/"
    - "/Ptyxis/"
    - "/(?i)emacs/"
    - '/org\.gnome\.Connections/'
modmap:
  - name: Global
    remap:
      CapsLock: LeftCtrl

  - name: AT Translated Set 2 keyboard
    device:
      only: 'AT Translated Set 2 keyboard'
    remap:
      Alt_L: LeftMeta

keymap:
  - name: Global
    remap:
      Super-Shift-v: Super-Shift-v
      C-Esc: { escape_next_key: true }
  - name: macOS like
    application:
      not: *terminals
    remap:
      # Cursor
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }

      # Forward/Backward word
      M-b: { with_mark: C-left }
      M-f: { with_mark: C-right }

      # Beginning/End of line
      C-a: { with_mark: home }
      C-e: { with_mark: end }

      Super-b: C-b
      Super-f: C-f
      Super-p: C-p
      Super-n: C-n

      Super-a: C-a

      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t
      Super-r: C-r
      Super-LeftBrace: Alt_L-Left
      Super-RightBrace: Alt_L-Right

  - name: deleting like Emacs
    application:
      not: *terminals
    exact_match: true
    remap:
      C-h: backspace
      C-d: delete
      C-k: [Shift-end, delete, { set_mark: false }]

      Super-d: C-d
      Super-k: C-k

  - name: Teminal
    application:
      only:
        - /(?i)terminal/
        - /Ptyxis/
    remap:
      Super-c: C-Shift-c
      Super-v: C-Shift-v

  - name: Gvim
    application:
      only: [ "/(?i)gvim/"]
    remap:
      Super-a: C-Shift-a
      Super-c: C-Shift-c
      Super-v: C-Shift-v

  - name: Browser
    application:
      only:
        - /browser/
        - /(?i)chromium/
        - /(?i)chrome/
    remap:
      # for browsing history
      Super-y: C-h
