# You may need:
# # echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/99-input.rules
# sudo udevadm trigger
# sudo udevadm control --reload-rules
#
# To allow xremap to fetch the focused app name using D-Bus,
# you need to enable the extension which is in:
#    https://extensions.gnome.org/extension/5060/xremap/
modmap:
  - name: Global
    remap:
      CapsLock: LeftCtrl

keymap:
  - name: macOS like
    application:
      not: [/terminal/]
    remap:
      # Cursor
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }

      # Forward/Backward word
      M-b: { with_mark: C-left }
      M-f: { with_mark: C-right }

      # Beginning/End of line
      C-a: { with_mark: home }
      C-e: { with_mark: end }

      # Deleting
      C-h: backspace
      C-d: delete
      C-k: [Shift-end, C-x, { set_mark: false }]
      C-y: [C-v, { set_mark: false }]

      Super-b: C-b
      Super-f: C-f
      Super-p: C-p
      Super-n: C-n

      Super-a: C-a
      Super-e: C-e

      Super-d: C-d
      Super-k: C-k
      Super-y: C-y

      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t
      Super-l: C-l

  - name: Teminal
    application:
      only: [/terminal/]
    remap:
      Super-c: C-Shift-c
      Super-v: C-Shift-v
